FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# Билдим внутри контейнера
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
# Устанавливаем только продакшн-зависимости
RUN npm ci --omit=dev
CMD ["npm", "start"]